//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class equivalent_td
    {
        public int id_categ { get; set; }
        public int id_type_cours { get; set; }
        public Nullable<double> ratio { get; set; }
    
        public virtual categorie categorie { get; set; }
        public virtual type_cours type_cours { get; set; }
    }
}
